name: Build Padavan RT-N14U

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup System Directory & Dependencies
        run: |
          sudo rm -rf /opt/rt-n56u
          sudo ln -s "$GITHUB_WORKSPACE" /opt/rt-n56u
          sudo apt update
          sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano \
          pkg-config autoconf automake make texinfo fakeroot ncurses-dev gettext \
          autopoint libelf-dev libssl-dev build-essential zlib1g-dev libgmp3-dev \
          libmpfr-dev libmpc-dev libudev-dev python-is-python3 help2man bc dos2unix

      - name: Build Toolchain
        run: |
          cd /opt/rt-n56u/toolchain-mipsel
          chmod +x * 2>/dev/null || true
          [ -f ./clean_sources ] && ./clean_sources || true
          [ -f ./clean_sources.sh ] && ./clean_sources.sh || true
          if [ -f ./build_toolchain ]; then
            ./build_toolchain
          elif [ -f ./build_toolchain.sh ]; then
            ./build_toolchain.sh
          fi

      - name: Build Firmware
        run: |
          cd /opt/rt-n56u/trunk
          chmod +x * 2>/dev/null || true
          cp -f configs/templates/RT-N14U.config .config
          [ -f ./clear_tree ] && ./clear_tree || true
          [ -f ./clear_tree.sh ] && ./clear_tree.sh || true
          if [ -f ./build_firmware ]; then
            fakeroot ./build_firmware RT-N14U
          elif [ -f ./build_firmware.sh ]; then
            fakeroot ./build_firmware.sh RT-N14U
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Padavan-BL201-Firmware
          path: /opt/rt-n56u/trunk/images/*.trx
