name: Build Padavan RT-N14U

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano \
          pkg-config autoconf automake make texinfo fakeroot ncurses-dev gettext \
          autopoint libelf-dev libssl-dev build-essential zlib1g-dev libgmp3-dev \
          libmpfr-dev libmpc-dev libudev-dev python-is-python3 help2man bc dos2unix

      - name: Build Toolchain
        run: |
          cd toolchain-mipsel
          chmod +x *.sh 2>/dev/null || true
          if [ -f ./clean_sources.sh ]; then ./clean_sources.sh; elif [ -f ./clean_sources ]; then ./clean_sources; fi
          if [ -f ./build_toolchain.sh ]; then ./build_toolchain.sh; elif [ -f ./build_toolchain ]; then ./build_toolchain; fi

      - name: Build Firmware
        run: |
          cd trunk
          chmod +x *.sh 2>/dev/null || true
          cp configs/templates/RT-N14U.config .config
          if [ -f ./clear_tree.sh ]; then ./clear_tree.sh; elif [ -f ./clear_tree ]; then ./clear_tree; fi
          if [ -f ./build_firmware.sh ]; then fakeroot ./build_firmware.sh; elif [ -f ./build_firmware ]; then fakeroot ./build_firmware; fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Padavan-BL201-Firmware
          path: trunk/images/*.trx
